# *European Call Option In Python*

*This is an example of the trinomial tree in Python that I did for my Financial Derivatives Course. It was made with the help of QuantPy's tutorial for the binomial tree, which is available here: https://github.com/TheQuantPy/youtube-tutorials/blob/8e64e19629cee840928b51baf4660e5c777e87e7/2021/003%20Jul-Sep/2021-07-06%20Binomial%20Option%20Pricing%20Model%20_%20Theory%20_%20Implementation%20in%20Python.ipynb*

*You can change the parameters to your liking.*

In [1]:
import numpy as np

In [2]:
#We set our parameters
S0 = 100 #initial stock price
K = 90 #strike price
r = 0.20 #risk-free rate (you will see why we chose this rate below)
N = 3 #time steps
u = 1 #up factor
d = -u #down factor
Pm = 0 #middle risk neutral probability

In [3]:
disc = np.exp(-r)
Pu = ((np.exp(r)-np.exp(d))/(np.exp(u)-np.exp(d)))-Pm*((1-np.exp(d))/(np.exp(u)-np.exp(d)))
Pd = 1 - Pu - Pm
print("Risk neutral probabilities:")
print("UP", Pu)
print("MIDDLE", Pm)
print("DOWN", Pd)
#create possible asset prices at maturity
S = np.zeros(2*N+1) #we create an array for asset prices at maturity
S[0] = S0*np.exp(d*N)
print(S[0])
for j in range(1, 2*N+1):
    S[j] = S[j-1]*np.exp(u) #stock price at up movement

print(S, " possible asset prices at maturity")

#create option values at maturity
C = np.zeros(2*N+1)
for j in range(0, 2*N+1):
    C[j] = max(0, S[j]-K) #the payoff at each node will be the difference between the stock price and strike price, or 0 if we're below the strike price
print(C, "possible payoffs at maturity")

#step backwards through tree, until we get to t=0
for i in np.arange(N, 0, -1):
        for j in range(0, 2*i-1):
                C[j] = disc*(Pu*C[j+2] + Pm*C[j+1] + Pd*C[j])
                print(C[:2*i-1])
print(C[0], "price at t=0")

Risk neutral probabilities:
UP 0.3631392316503326
MIDDLE 0
DOWN 0.6368607683496674
4.978706836786395
[   4.97870684   13.53352832   36.78794412  100.          271.82818285
  738.90560989 2008.55369232]  possible asset prices at maturity
[   0.            0.            0.           10.          181.82818285
  648.90560989 1918.55369232] possible payoffs at maturity
[  0.           0.           0.          10.         181.82818285]
[  0.           2.97313257   0.          10.         181.82818285]
[  0.           2.97313257  54.05992918  10.         181.82818285]
[  0.           2.97313257  54.05992918 198.14241507 181.82818285]
[  0.           2.97313257  54.05992918 198.14241507 665.21984212]
[16.0727336   2.97313257 54.05992918]
[16.0727336  60.46061003 54.05992918]
[ 16.0727336   60.46061003 225.96647055]
[75.56343176]
75.56343175573598 price at t=0


**Result:** *The price of the European Option with K=90 should be $68,19*

**Now we do the binomial model**

In [4]:
S0 = 100 #initial stock price
K = 90 #strike price
r = 0.20 #risk-free rate (you will see why we chose this rate below)
N = 3 #time steps
u = np.exp(1) #up factor
d = 1/u #down factor


q = (np.exp(r) - d) / (u-d)
disc = np.exp(-r)

 # initialise asset prices at maturity - Time step N
S = np.zeros(N+1)
S[0] = S0*d**N
for j in range(1,N+1):
    S[j] = S[j-1]*u/d

# initialise option values at maturity
C = np.zeros(N+1)
for j in range(0,N+1):
    C[j] = max(0, S[j]-K)

# step backwards through tree
for i in np.arange(N,0,-1):
    for j in range(0,i):
        C[j] = disc * ( q*C[j+1] + (1-q)*C[j] )

print(C[0])

75.56343175573603


*Using the trinoimal model and setting the middle movement to 0 effectively gives us the binomial model and the same price as in the actual binomial model.*